package com.EyeOfHarmonyBuffer.common.material;

import bartworks.system.material.Werkstoff;
import gregtech.api.enums.OrePrefixes;
import gregtech.api.enums.TextureSet;

import static com.EyeOfHarmonyBuffer.utils.TextLocalization.*;

public class EOHBMaterialPool implements Runnable{

    public static final int OFFSET_ID = 30_000;

    public static final Werkstoff EOHBCatalyst = new Werkstoff(
        new short[]{128, 45, 200},
        EOHB_Harmony,
        EOHB_Harmony_Tooltip,
        new Werkstoff.Stats()
            .setBlastFurnace(true)
            .disableAutoGeneratedBlastFurnaceRecipes()
            .disableAutoGeneratedVacuumFreezerRecipes(),
        Werkstoff.Types.MIXTURE,
        new Werkstoff.GenerationFeatures()
            .onlyDust()
            .addPrefix(OrePrefixes.ingot),
        OFFSET_ID + 1,
        TextureSet.SET_SHINY
    );

    public static final Werkstoff OriginiumWasteLiquid = new Werkstoff(
        new short[]{90, 150, 40},
        EOHB_OriginiumWasteLiquid,
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.ELEMENT,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 2,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff ArsenicImpact = new Werkstoff(
        new short[] { 220, 222, 230 },
        EOHB_ArsenicImpact,
        EOHB_ArsenicImpact_Tooltip,
        new Werkstoff.Stats()
            .setGas(false)
            .setBlastFurnace(true)
            .setMeltingPoint(1350)
            .setMeltingVoltage(120)
            .disableAutoGeneratedBlastFurnaceRecipes()
            .disableAutoGeneratedVacuumFreezerRecipes(),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .addMetalItems()
            .addCraftingMetalWorkingItems()
            .addPrefix(OrePrefixes.dust)
            .addPrefix(OrePrefixes.dustSmall)
            .addPrefix(OrePrefixes.dustTiny)
            .addMolten()
            .addCells()
            .setBlacklist(OrePrefixes.ore)
            .setBlacklist(OrePrefixes.oreBlackgranite)
            .setBlacklist(OrePrefixes.oreRedgranite)
            .setBlacklist(OrePrefixes.oreEnd)
            .setBlacklist(OrePrefixes.oreNether),
        OFFSET_ID + 3,
        TextureSet.SET_SHINY
    );

    public static final Werkstoff Hoyomixium = new Werkstoff(
        new short[] { 120, 200, 255 },
        EOHB_Hoyomixium,
        EOHB_Hoyomixium_Tooltip,
        new Werkstoff.Stats()
            .setBlastFurnace(true)
            .setMeltingPoint(2100)
            .setMeltingVoltage(180)
            .setMass(540)
            .setProtons(118)
            .disableAutoGeneratedBlastFurnaceRecipes()
            .disableAutoGeneratedVacuumFreezerRecipes(),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addPrefix(OrePrefixes.dust)
            .addPrefix(OrePrefixes.ingot)
            .addMolten(),
        OFFSET_ID + 4,
        TextureSet.SET_METALLIC
    );

    public static Werkstoff.GenerationFeatures gf = new Werkstoff.GenerationFeatures();

    @Override
    public void run() {
        for (var prefix : OrePrefixes.values()) {
            gf.addPrefix(prefix);
        }
        gf.removePrefix(OrePrefixes.ore);
    }

    public static String subscriptNumbers(String input) {
        return input
            .replace("0", "₀")
            .replace("1", "₁")
            .replace("2", "₂")
            .replace("3", "₃")
            .replace("4", "₄")
            .replace("5", "₅")
            .replace("6", "₆")
            .replace("7", "₇")
            .replace("8", "₈")
            .replace("9", "₉");
    }
}
