package com.EyeOfHarmonyBuffer.common.material;

import bartworks.system.material.Werkstoff;
import gregtech.api.enums.OrePrefixes;
import gregtech.api.enums.TextureSet;

import static com.EyeOfHarmonyBuffer.utils.TextLocalization.EOHB_Harmony;
import static com.EyeOfHarmonyBuffer.utils.TextLocalization.EOHB_Harmony_Tooltip;

public class EOHBMaterialPool implements Runnable{

    public static final int OFFSET_ID = 30_000;

    public static final Werkstoff EOHBCatalyst = new Werkstoff(
        new short[]{128, 45, 200},
        EOHB_Harmony,
        EOHB_Harmony_Tooltip,
        new Werkstoff.Stats()
            .setToxic(true)
            .setBlastFurnace(true)
            .disableAutoGeneratedBlastFurnaceRecipes()
            .disableAutoGeneratedVacuumFreezerRecipes(),
        Werkstoff.Types.MIXTURE,
        new Werkstoff.GenerationFeatures()
            .onlyDust()
            .addPrefix(OrePrefixes.ingot),
        OFFSET_ID + 1,
        TextureSet.SET_SHINY
    );

    public static final Werkstoff EOHBSolution = new Werkstoff(
        new short[]{64, 180, 240},
        "EOHB-Solution",
        subscriptNumbers("(EOHB)(H2O)"),
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.ELEMENT,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 2,
        TextureSet.SET_FLUID
    );

    public static Werkstoff.GenerationFeatures gf = new Werkstoff.GenerationFeatures();

    @Override
    public void run() {
        for (var prefix : OrePrefixes.values()) {
            gf.addPrefix(prefix);
        }
        gf.removePrefix(OrePrefixes.ore);
    }

    public static String subscriptNumbers(String input) {
        return input
            .replace("0", "₀")
            .replace("1", "₁")
            .replace("2", "₂")
            .replace("3", "₃")
            .replace("4", "₄")
            .replace("5", "₅")
            .replace("6", "₆")
            .replace("7", "₇")
            .replace("8", "₈")
            .replace("9", "₉");
    }
}
