package com.EyeOfHarmonyBuffer.common.material;

import bartworks.system.material.Werkstoff;
import gregtech.api.enums.OrePrefixes;
import gregtech.api.enums.TextureSet;

import static com.EyeOfHarmonyBuffer.utils.TextLocalization.*;

public class EOHBMaterialPool implements Runnable{

    public static final int OFFSET_ID = 30_000;

    public static final Werkstoff EOHBCatalyst = new Werkstoff(
        new short[]{128, 45, 200},
        "Harmony",
        EOHB_Harmony_Tooltip,
        new Werkstoff.Stats()
            .setBlastFurnace(true)
            .disableAutoGeneratedBlastFurnaceRecipes()
            .disableAutoGeneratedVacuumFreezerRecipes(),
        Werkstoff.Types.MIXTURE,
        new Werkstoff.GenerationFeatures()
            .onlyDust()
            .addPrefix(OrePrefixes.ingot),
        OFFSET_ID + 1,
        TextureSet.SET_SHINY
    );

    public static final Werkstoff OriginiumWasteLiquid = new Werkstoff(
        new short[]{90, 150, 40},
        "Originium Waste Liquid",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.ELEMENT,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 2,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff ArsenicImpact = new Werkstoff(
        new short[] { 220, 222, 230 },
        "Arsenic Impact",
        EOHB_ArsenicImpact_Tooltip,
        new Werkstoff.Stats()
            .setGas(false)
            .setBlastFurnace(true)
            .setMeltingPoint(1350)
            .setMeltingVoltage(120)
            .disableAutoGeneratedBlastFurnaceRecipes()
            .disableAutoGeneratedVacuumFreezerRecipes(),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .addMetalItems()
            .addCraftingMetalWorkingItems()
            .addPrefix(OrePrefixes.dust)
            .addPrefix(OrePrefixes.dustSmall)
            .addPrefix(OrePrefixes.dustTiny)
            .addMolten()
            .addCells()
            .removePrefix(OrePrefixes.ore)
            .removePrefix(OrePrefixes.oreBlackgranite)
            .removePrefix(OrePrefixes.oreRedgranite)
            .removePrefix(OrePrefixes.oreEnd)
            .removePrefix(OrePrefixes.oreNether),
        OFFSET_ID + 3,
        TextureSet.SET_SHINY
    );

    public static final Werkstoff Hoyomixium = new Werkstoff(
        new short[] { 120, 200, 255 },
        "Hoyomixium",
        EOHB_Hoyomixium_Tooltip,
        new Werkstoff.Stats()
            .setBlastFurnace(true)
            .setMeltingPoint(2100)
            .setMeltingVoltage(180)
            .setMass(540)
            .setProtons(118)
            .disableAutoGeneratedBlastFurnaceRecipes()
            .disableAutoGeneratedVacuumFreezerRecipes(),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addPrefix(OrePrefixes.dust)
            .addPrefix(OrePrefixes.ingot)
            .addMolten(),
        OFFSET_ID + 4,
        TextureSet.SET_METALLIC
    );

    public static final Werkstoff PrecipitationAcid = new Werkstoff(
        new short[] { 255, 170, 0 },
        "Precipitation Acid",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 5,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff CupriumSolution = new Werkstoff(
        new short[] { 205, 35, 35 },
        "Cuprium Solution",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 6,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff InertXirconEffluent = new Werkstoff(
        new short[] { 20, 95, 145 },
        "Inert Xircon Effluent",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 7,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff HetoniteSolution = new Werkstoff(
        new short[] { 220, 55, 70 },
        "Hetonite Solution",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 8,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff JinCaoSolution = new Werkstoff(
        new short[] { 225, 245, 185 },
        "JinCao Solution",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 9,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff XirconEffluent = new Werkstoff(
        new short[] { 35, 150, 175 },
        "Xircon Effluent",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 10,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff Sewage = new Werkstoff(
        new short[] { 125, 125, 125 },
        "Sewage",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 11,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff YaZhenSolution = new Werkstoff(
        new short[] { 195, 220, 75 },
        "YaZhen Solution",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 12,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff LiquidXiranite = new Werkstoff(
        new short[] { 60, 185, 85 },
        "Liquid Xiranite",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 13,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff LiquidHeavyXiranite = new Werkstoff(
        new short[] { 25, 105, 45 },
        "Liquid Heavy Xiranite",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 14,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff LiquefiedOrundum = new Werkstoff(
        new short[] { 219, 165, 82 },
        "Liquefied Orundum",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 15,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff CrudeLiquefiedOrundum = new Werkstoff(
        new short[] { 153, 116, 57 },
        "Crude Liquefied Orundum",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 16,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff HighEnergyOrundumSolvent = new Werkstoff(
        new short[] { 255, 200, 100 },
        "High-Energy Orundum Solvent",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 17,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff UnstableOrundumSolvent = new Werkstoff(
        new short[] { 255, 80, 0 },
        "Unstable Orundum Solvent",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 18,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff ContaminatedOrundumSlurry = new Werkstoff(
        new short[] { 104, 96, 72 },
        "Contaminated Orundum Slurry",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 19,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff StabilizedHigh_EnergyOrundumSolvent = new Werkstoff(
        new short[] { 0, 210, 255 },
        "Stabilized High-Energy Orundum Solvent",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 20,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff AnomalousEnergyCondensate = new Werkstoff(
        new short[] { 150, 0, 200 },
        "Anomalous Energy Condensate",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 21,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff AdvancedOrundumFuelPrecursor = new Werkstoff(
        new short[] { 150, 0, 200 },
        "Advanced Orundum Fuel Precursor",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 22,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff Acridgen = new Werkstoff(
        new short[] { 255, 255, 0 },
        "Acridgen",
        new Werkstoff.Stats().setGas(true),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 23,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff Aquagen = new Werkstoff(
        new short[] { 128, 128, 128 },
        "Aquagen",
        new Werkstoff.Stats().setGas(true),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 24,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff Inergen = new Werkstoff(
        new short[] { 150, 200, 255 },
        "Inergen",
        new Werkstoff.Stats().setGas(true),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 25,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff Xiragen = new Werkstoff(
        new short[] { 150, 255, 150 },
        "Xiragen",
        new Werkstoff.Stats().setGas(true),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 26,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff HeavyXiragen = new Werkstoff(
        new short[] { 0, 100, 0 },
        "Heavy Xiragen",
        new Werkstoff.Stats().setGas(true),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 27,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff CupriumGas = new Werkstoff(
        new short[] { 255, 150, 150 },
        "Cuprium Gas",
        new Werkstoff.Stats().setGas(true),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 28,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff HetoniteGas = new Werkstoff(
        new short[] { 255, 0, 0 },
        "Hetonite Gas",
        new Werkstoff.Stats().setGas(true),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 29,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff PyrroliteGas = new Werkstoff(
        new short[] { 255, 80, 0 },
        "Pyrrolite Gas",
        new Werkstoff.Stats().setGas(true),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 30,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff HighEnergyGas = new Werkstoff(
        new short[] { 255, 200, 100 },
        "High-Energy Gas",
        new Werkstoff.Stats().setGas(true),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 31,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff TangZhi = new Werkstoff(
        new short[] { 240, 200, 140 },
        "Sugar Syrup",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 32,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff TongJiRongYe = new Werkstoff(
        new short[] { 150, 190, 220 },
        "Ketone Solution",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 33,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff FaJiaoTangJiang = new Werkstoff(
        new short[] { 180, 140, 60 },
        "Fermented Sugar Syrup",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 34,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff TongJiJuHeWu = new Werkstoff(
        new short[] { 160, 170, 190 },
        "Ketone Polymer",
        new Werkstoff.Stats(),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .onlyDust(),
        OFFSET_ID + 35,
        TextureSet.SET_SHINY
    );

    public static final Werkstoff FuHeTangJiang = new Werkstoff(
        new short[] { 230, 170, 90 },
        "Compound Sugar Syrup",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 36,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff TangRongYe = new Werkstoff(
        new short[] { 250, 240, 200 },
        "Sugar Solution",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 37,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff JuZhiRongJiang = new Werkstoff(
        new short[] { 220, 190, 130 },
        "Polyester Melt",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 38,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff FuHeJuZhiJiang = new Werkstoff(
        new short[] { 200, 170, 110 },
        "Compound Polyester Slurry",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 39,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff YiTieJiang = new Werkstoff(
        new short[] { 130, 140, 150 },
        "Oriron Slurry",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 40,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff FuHeYiTieJiang = new Werkstoff(
        new short[] { 100, 110, 120 },
        "Compound Oriron Slurry",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 41,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff BoYiFen = new Werkstoff(
        new short[] { 200, 205, 210 },
        "Platinum-Iridium Dust",
        new Werkstoff.Stats(),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .onlyDust(),
        OFFSET_ID + 42,
        TextureSet.SET_SHINY
    );

    public static final Werkstoff DianJiJiang = new Werkstoff(
        new short[] { 170, 175, 180 },
        "Electrode Slurry",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 43,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff JingZhiDianJiJiang = new Werkstoff(
        new short[] { 150, 155, 165 },
        "Refined Electrode Slurry",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 44,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff JingTiJiang = new Werkstoff(
        new short[] { 190, 120, 200 },
        "Crystal Slurry",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 45,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff ShiKeJingTiJiang = new Werkstoff(
        new short[] { 180, 140, 210 },
        "Etched Crystal Slurry",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 46,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff DuBoJingTiJiang = new Werkstoff(
        new short[] { 210, 180, 230 },
        "Platinum-Plated Crystal Slurry",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 47,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff ChiHeJinPeiLiao = new Werkstoff(
        new short[] { 230, 90, 40 },
        "Blazing Alloy Feedstock",
        new Werkstoff.Stats(),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .onlyDust(),
        OFFSET_ID + 48,
        TextureSet.SET_SHINY
    );

    public static final Werkstoff ChiHeJinJiang = new Werkstoff(
        new short[] { 220, 100, 50 },
        "Blazing Alloy Slurry",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 49,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff JingLianChiHeJinJiang = new Werkstoff(
        new short[] { 240, 130, 80 },
        "Refined Blazing Alloy Slurry",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 50,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff WenDingGaoNengQiTi = new Werkstoff(
        new short[] { 255, 230, 150 },
        "Stabilized High-Energy Gas",
        new Werkstoff.Stats().setGas(true),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 51,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff GaoNengYeTi = new Werkstoff(
        new short[] { 255, 200, 80 },
        "High-Energy Liquid",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 52,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff NingJiaoQianTi = new Werkstoff(
        new short[] { 200, 230, 220 },
        "Gel Precursor",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 53,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff JiaoLianNingJiao = new Werkstoff(
        new short[] { 180, 220, 200 },
        "Crosslinked Gel",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 54,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff NiuZhuanChunJiang = new Werkstoff(
        new short[] { 170, 220, 160 },
        "Twisted Alcohol Slurry",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 55,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff ChunHuaNiuZhuanChunJiang = new Werkstoff(
        new short[] { 190, 235, 175 },
        "Purified Twisted Alcohol Slurry",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 56,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff ChuanTongRongJi = new Werkstoff(
        new short[] { 210, 200, 180 },
        "Traditional Solvent",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 57,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff GaiXingRongJi = new Werkstoff(
        new short[] { 190, 170, 160 },
        "Modified Solvent",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 58,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff NaiSuanJianRongJi = new Werkstoff(
        new short[] { 200, 160, 140 },
        "Acid-Alkali Resistant Solvent",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 59,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff RuHuaJi = new Werkstoff(
        new short[] { 235, 230, 200 },
        "Emulsifier",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 60,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff JingZhiQieXiaoYe = new Werkstoff(
        new short[] { 180, 210, 230 },
        "Refined Cutting Fluid",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 61,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff XiFuJiang = new Werkstoff(
        new short[] { 150, 150, 150 },
        "Adsorption Slurry",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 62,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff NingJieJiang = new Werkstoff(
        new short[] { 130, 130, 140 },
        "Condensation Slurry",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 63,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff HuanTingDanTi = new Werkstoff(
        new short[] { 200, 220, 235 },
        "Cyclic Hydrocarbon Monomer",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 64,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff HuanTingJuHeWu = new Werkstoff(
        new short[] { 180, 200, 220 },
        "Cyclic Hydrocarbon Polymer",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 65,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff GangYuFen = new Werkstoff(
        new short[] { 235, 120, 130 },
        "Corundum Dust",
        new Werkstoff.Stats(),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .onlyDust(),
        OFFSET_ID + 66,
        TextureSet.SET_SHINY
    );

    public static final Werkstoff MengKuangJingFen = new Werkstoff(
        new short[] { 150, 150, 170 },
        "Refined Manganese Dust",
        new Werkstoff.Stats(),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .onlyDust(),
        OFFSET_ID + 67,
        TextureSet.SET_SHINY
    );

    public static final Werkstoff YanMoJiang = new Werkstoff(
        new short[] { 200, 190, 180 },
        "Grinding Slurry",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 68,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff JingZhiYanMoJiang = new Werkstoff(
        new short[] { 210, 200, 190 },
        "Refined Grinding Slurry",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 69,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff KuangWuJiang = new Werkstoff(
        new short[] { 120, 130, 150 },
        "Mineral Slurry",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 70,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff JingZhiKuangWuJiang = new Werkstoff(
        new short[] { 140, 150, 170 },
        "Refined Mineral Slurry",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 71,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff FangSiYe = new Werkstoff(
        new short[] { 220, 210, 190 },
        "Spinning Solution",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 72,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff JingZhiFangSiYe = new Werkstoff(
        new short[] { 230, 220, 200 },
        "Refined Spinning Solution",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 73,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff NongSuoFangSiYe = new Werkstoff(
        new short[] { 240, 230, 205 },
        "Concentrated Spinning Solution",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 74,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff CuZhiQieXiaoYe = new Werkstoff(
        new short[] { 190, 205, 220 },
        "Raw Cutting Fluid",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 75,
        TextureSet.SET_FLUID
    );

    public static final Werkstoff GaoJieJingLianYe = new Werkstoff(
        new short[] { 160, 90, 220 },
        "High-Grade Refining Fluid",
        new Werkstoff.Stats().setGas(false),
        Werkstoff.Types.MATERIAL,
        new Werkstoff.GenerationFeatures()
            .disable()
            .addCells(),
        OFFSET_ID + 76,
        TextureSet.SET_FLUID
    );

    public static Werkstoff.GenerationFeatures gf = new Werkstoff.GenerationFeatures();

    @Override
    public void run() {
        for (OrePrefixes prefix : OrePrefixes.VALUES) {
            gf.addPrefix(prefix);
        }
        gf.removePrefix(OrePrefixes.ore);
    }

    public static String subscriptNumbers(String input) {
        return input
            .replace("0", "₀")
            .replace("1", "₁")
            .replace("2", "₂")
            .replace("3", "₃")
            .replace("4", "₄")
            .replace("5", "₅")
            .replace("6", "₆")
            .replace("7", "₇")
            .replace("8", "₈")
            .replace("9", "₉");
    }
}
