package com.EyeOfHarmonyBuffer.common.Machine;

import com.EyeOfHarmonyBuffer.utils.TextLocalization;
import com.gtnewhorizon.structurelib.alignment.constructable.IConstructable;
import com.gtnewhorizon.structurelib.alignment.constructable.ISurvivalConstructable;
import com.gtnewhorizon.structurelib.structure.IStructureDefinition;
import com.gtnewhorizon.structurelib.structure.ISurvivalBuildEnvironment;
import com.gtnewhorizon.structurelib.structure.StructureDefinition;
import goodgenerator.blocks.tileEntity.MTEMultiNqGenerator;
import goodgenerator.blocks.tileEntity.base.MTETooltipMultiBlockBaseEM;
import gregtech.api.GregTechAPI;
import gregtech.api.enums.Textures;
import gregtech.api.interfaces.ITexture;
import gregtech.api.interfaces.metatileentity.IMetaTileEntity;
import gregtech.api.interfaces.tileentity.IGregTechTileEntity;
import gregtech.api.objects.GTRenderedTexture;
import gregtech.api.render.TextureFactory;
import gregtech.api.util.MultiblockTooltipBuilder;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.util.ForgeDirection;
import tectech.thing.casing.TTCasingsContainer;

import static com.EyeOfHarmonyBuffer.utils.TextLocalization.*;
import static com.gtnewhorizon.structurelib.structure.StructureUtility.ofBlock;
import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;
import static gregtech.api.enums.Textures.BlockIcons.BLOCK_PLASCRETE;

public class EOHB_WindTurbine extends MTETooltipMultiBlockBaseEM implements IConstructable, ISurvivalConstructable {

    private IStructureDefinition<EOHB_WindTurbine> multiDefinition = null;

    public EOHB_WindTurbine(int aID, String aName, String aNameRegional) {
        super(aID, aName, aNameRegional);
    }

    @Override
    public IStructureDefinition<EOHB_WindTurbine> getStructure_EM() {
        if(multiDefinition == null) {
            multiDefinition = StructureDefinition.<EOHB_WindTurbine>builder()
                .addShape(
                    mName,
                    transpose(
                        new String[][]{
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","         DDDDD         ","         DDDDD         ","         DDDDD         ","         DDDDD         ","         DDDDD         ","         DDDDD         ","         DDDDD         ","         DDDDD         ","         DDDDD         ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","         DDDDD         ","                       ","         DDDDD         ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        DDDDDDD        ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","          AAA          ","         DDDDD         ","          BBB          ","         D   D         ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        DAADAAD        ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","          AAA          ","         DDDDD         ","          B B          ","         D   D         ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        DAADAAD        ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","          AAA          ","         DDDDD         ","          BBB          ","         D   D         ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        DAADAAD        ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","         DDDDD         ","                       ","         DDDDD         ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        DDDDDDD        ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","         DDDDD         ","         DDDDD         ","         DD DD         ","         DDDDD         ","         DDDDD         ","         DDDDD         ","         DDDDD         ","         DDDDD         ","         DDDDD         ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","          DDD          ","          D D          ","          DDD          ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","          DDD          ","          D D          ","          DDD          ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","          DDD          ","          D D          ","          DDD          ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","          DDD          ","          D D          ","          DDD          ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","          DDD          ","          D D          ","          DDD          ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","          DDD          ","          D D          ","          DDD          ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","          DDD          ","          D D          ","          DDD          ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","          DDD          ","          D D          ","          DDD          ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","          DDD          ","          D D          ","          DDD          ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","          DDD          ","          D D          ","          DDD          ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","          DDD          ","          D D          ","          DDD          ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","          DDD          ","          D D          ","          DDD          ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","         CCCCC         ","         CDDDC         ","         CD DC         ","         CDDDC         ","         CCCCC         ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","         CDDDC         ","         DDDDD         ","         DD DD         ","         DDDDD         ","         CDDDC         ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","         CDDDC         ","         D   D         ","         D   D         ","         D   D         ","         CDDDC         ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","         CDDDC         ","         D   D         ","         D   D         ","         D   D         ","         CDDDC         ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","         CDDDC         ","         D   D         ","         D   D         ","         D   D         ","         CDDDC         ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","         CDDDC         ","         D   D         ","         D   D         ","         D   D         ","         CDDDC         ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","         CDDDC         ","         D   D         ","         D   D         ","         D   D         ","         CDDDC         ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","         CDDDC         ","         D   D         ","         D   D         ","         D   D         ","         CDDDC         ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","         CDDDC         ","         D   D         ","         D   D         ","         D   D         ","         CDDDC         ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","         CDDDC         ","         D   D         ","         D   D         ","         D   D         ","         CDDDC         ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","         CDDDC         ","         D   D         ","         D   D         ","         D   D         ","         CDDDC         ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","         CDDDC         ","         D   D         ","         D   D         ","         D   D         ","         CDDDC         ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","         CDDDC         ","         D   D         ","         D   D         ","         D   D         ","         CDDDC         ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","         CDDDC         ","         D   D         ","         D   D         ","         D   D         ","         CDDDC         ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CCCCCCC        ","        CDDDDDC        ","        CD   DC        ","        CD   DC        ","        CD   DC        ","        CDDDDDC        ","        CCCCCCC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDDDDDC        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDDDDDC        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDDDDDC        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDDDDDC        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDDDDDC        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDDDDDC        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDDDDDC        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDDDDDC        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDDDDDC        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDDDDDC        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDDDDDC        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDDDDDC        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        D     D        ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CCCCCCC        ","       CDDDDDDDC       ","       CD     DC       ","       CD     DC       ","       CD     DC       ","       CD     DC       ","       CD     DC       ","       CDDDDDDDC       ","        CCCCCCC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDDDDDC        ","       CD     DC       ","       D       D       ","       D       D       ","       D       D       ","       D       D       ","       D       D       ","       CD     DC       ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDDDDDC        ","       CD     DC       ","       D       D       ","       D       D       ","       D       D       ","       D       D       ","       D       D       ","       CD     DC       ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDDDDDC        ","       CD     DC       ","       D       D       ","       D       D       ","       D       D       ","       D       D       ","       D       D       ","       CD     DC       ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDDDDDC        ","       CD     DC       ","       D       D       ","       D       D       ","       D       D       ","       D       D       ","       D       D       ","       CD     DC       ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDDDDDC        ","       CD     DC       ","       D       D       ","       D       D       ","       D       D       ","       D       D       ","       D       D       ","       CD     DC       ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDDDDDC        ","       CD     DC       ","       D       D       ","       D       D       ","       D       D       ","       D       D       ","       D       D       ","       CD     DC       ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDDDDDC        ","       CD     DC       ","       D       D       ","       D       D       ","       D       D       ","       D       D       ","       D       D       ","       CD     DC       ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDDDDDC        ","       CD     DC       ","       D       D       ","       D       D       ","       D       D       ","       D       D       ","       D       D       ","       CD     DC       ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDD DDC        ","       CD     DC       ","       D       D       ","       D       D       ","       D       D       ","       D       D       ","       D       D       ","       CD     DC       ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","                       ","        CDD DDC        ","       CD     DC       ","       D       D       ","       D       D       ","       D       D       ","       D       D       ","       D       D       ","       CD     DC       ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","                       ","                       ","                       ","                       ","        CDDDDDC        ","       CDDDDDDDC       ","      CDDDDDDDDDC      ","      DDDDDDDDDDD      ","      DDDDDDDDDDD      ","      DDDDDDDDDDD      ","      DDDDDDDDDDD      ","      DDDDDDDDDDD      ","      CDDDDDDDDDC      ","       CDDDDDDDC       ","        CDDDDDC        ","                       ","                       ","                       ","                       ","                       ","                       "},
                            {"                       ","                       ","        DDDDDDD        ","      DDDDDDDDDDD      ","     DDDDDDDDDDDDD     ","    DDDDDDDDDDDDDDD    ","   DDDDDDDDDDDDDDDDD   ","   DDDDDDDDDDDDDDDDD   ","  DDDDDDDDDDDDDDDDDDD  ","  DDDDDDDDDDDDDDDDDDD  ","  DDDDDDDDDDDDDDDDDDD  ","  DDDDDDDDDDDDDDDDDDD  ","  DDDDDDDDDDDDDDDDDDD  ","  DDDDDDDDDDDDDDDDDDD  ","  DDDDDDDDDDDDDDDDDDD  ","   DDDDDDDDDDDDDDDDD   ","   DDDDDDDDDDDDDDDDD   ","    DDDDDDDDDDDDDDD    ","     DDDDDDDDDDDDD     ","      DDDDDDDDDDD      ","        DDDDDDD        ","                       ","                       "},
                            {"        DDD~DDD        ","      DDDDDDDDDDD      ","    DDDDDDDDDDDDDDD    ","   DDDDDDDDDDDDDDDDD   ","  DDDDDDDDDDDDDDDDDDD  ","  DDDDDDDDDDDDDDDDDDD  "," DDDDDDDDDDDDDDDDDDDDD "," DDDDDDDDDDDDDDDDDDDDD ","DDDDDDDDDDDDDDDDDDDDDDD","DDDDDDDDDDDDDDDDDDDDDDD","DDDDDDDDDDDDDDDDDDDDDDD","DDDDDDDDDDDDDDDDDDDDDDD","DDDDDDDDDDDDDDDDDDDDDDD","DDDDDDDDDDDDDDDDDDDDDDD","DDDDDDDDDDDDDDDDDDDDDDD"," DDDDDDDDDDDDDDDDDDDDD "," DDDDDDDDDDDDDDDDDDDDD ","  DDDDDDDDDDDDDDDDDDD  ","  DDDDDDDDDDDDDDDDDDD  ","   DDDDDDDDDDDDDDDDD   ","    DDDDDDDDDDDDDDD    ","      DDDDDDDDDDD      ","        DDDDDDD        "}
                        }
                    )
                )
                .addElement('A',ofBlock(GregTechAPI.sBlockCasings3,11))
                .addElement('D',ofBlock(GregTechAPI.sBlockReinforced,2))
                .addElement('B',ofBlock(TTCasingsContainer.sBlockCasingsBA0, 7))
                .addElement('C',ofBlock(GregTechAPI.sBlockFrames,305))
                .build();
        }
        return multiDefinition;
    }

    @Override
    protected MultiblockTooltipBuilder createTooltip() {
        final MultiblockTooltipBuilder tt = new MultiblockTooltipBuilder();
        tt.addMachineType(Tooltip_WindTurbine_MachineType)
            .addInfo(Tooltip_WindTurbine_Controller)
/*            .addInfo()
            .addInfo()
            .addInfo()*/
            .addSeparator()
            .addInputBus(add_InputBus,1)
            .addInfo(TextLocalization.StructureTooComplex)
            .addInfo(TextLocalization.BLUE_PRINT_INFO)
            .toolTipFinisher(TextLocalization.ModName);
        return tt;
    }

    @Override
    public void construct(ItemStack itemStack, boolean hintsOnly) {
        structureBuild_EM(mName, 11, 59, 0, itemStack, hintsOnly);
    }

    @Override
    public boolean checkMachine_EM(IGregTechTileEntity aBaseMetaTileEntity, ItemStack aStack) {
        return structureCheck_EM(mName, 11, 59, 0) && mMaintenanceHatches.size() == 1
            && mDynamoHatches.size() + eDynamoMulti.size() == 1;
    }

    @Override
    public int survivalConstruct(ItemStack stackSize, int elementBudget, ISurvivalBuildEnvironment env) {
        if (mMachine) return -1;
        return survivialBuildPiece(mName, stackSize, 11, 59, 0, elementBudget, env, false, true);
    }

    @Override
    public IMetaTileEntity newMetaEntity(IGregTechTileEntity aTileEntity) {
        return new EOHB_WindTurbine(this.mName);
    }

    public EOHB_WindTurbine(String name){
        super(name);
    }

    @Override
    public int getMaxEfficiency(ItemStack aStack) { return 0; }

    @Override
    public int getPollutionPerTick(ItemStack aStack) { return 0; }

    @Override
    public int getDamageToComponent(ItemStack aStack) { return 0; }

    @Override
    public boolean explodesOnComponentBreak(ItemStack aStack) { return false; }

    @Override
    public boolean isCorrectMachinePart(ItemStack aStack) {
        return true;
    }

    @Override
    @SuppressWarnings("ALL")
    public ITexture[] getTexture(
        IGregTechTileEntity aBaseMetaTileEntity,
        ForgeDirection side,
        ForgeDirection facing,
        int colorIndex,
        boolean aActive,
        boolean aRedstone
    ){
        if(side == facing){
            if (aActive) return new ITexture[]{
                TextureFactory.of(BLOCK_PLASCRETE),
                new GTRenderedTexture(Textures.BlockIcons.NAQUADAH_REACTOR_SOLID_FRONT_ACTIVE), TextureFactory.builder()
                .addIcon(Textures.BlockIcons.NAQUADAH_REACTOR_SOLID_FRONT_ACTIVE_GLOW)
                .glow()
                .build()
            };
            else return new ITexture[]{
                TextureFactory.of(BLOCK_PLASCRETE),
                new GTRenderedTexture(Textures.BlockIcons.NAQUADAH_REACTOR_SOLID_FRONT)
            };
        }
        return new ITexture[]{TextureFactory.of(BLOCK_PLASCRETE)};
    }
}
