# ASCII-ONLY (PowerShell 5.1 reads BOM-less .ps1 as ANSI; Chinese comments silently
# swallow the next code line -- this file must stay ASCII).
#
# fingerprint_config.ps1 -- measurement provenance, DIMENSION COLLECTOR (phase B).
#
# WHY THIS EXISTS: the acceptance output directory was keyed on the SRC fingerprint
# alone, and the per-probe logs are Force-removed on start, so a run in a DIFFERENT
# configuration silently deleted the previous evidence. Two independent distortions
# were later found: the WORLD caliber (PlateField.WORLD_IS_TALOS, formerly TALOS_TERRAIN) and the SEED caliber (bare vs
# derived seed: 6 gates + 52 probes). Neither was in the measurement identity.
#
# DIMENSIONS
#   D-CLASSES : regenerate cfg_classes.txt from the SOURCE TREE (grep), never hand-kept.
#   D-SWITCHES: run P900 through run_one_probe.bat (SAME env/flag as the gates).
#   D-PROBES  : SHA256 over probe/*.java + the four runner scripts.
#   D-ENV     : whitelist of EOH_* variables.
#   D-SEED    : PROXY count of bare 1022228679L literals in probe sources.
#   D-CONFIG  : run/config/TalosConfig.cfg if present (Forge cfg classes cannot be
#               reflected without Forge, so the FILE is hashed instead).
#
# STDOUT: machine-readable KEY=VALUE lines (CFGFP/SRCFP/WORLD/SWITCHCOUNT/SEEDBARE)
#
# PARAMETERS
#   -NoRebuild  Do NOT run `runprobe4.bat ... --build-only` as a recovery step. That
#               rebuild begins with `rmdir /S /Q out`, so a caller that runs WHILE an
#               acceptance run is live (judge_acceptance.ps1 recomputes the stamp on
#               every judgement) would delete the class tree under a live JVM. With
#               this switch a missing/stale dump is FATAL (exit 5), not destructive.
param([switch]$NoRebuild)

$ErrorActionPreference = 'Stop'
$rootDir   = 'K:\moder\EyeOfHarmonyBuffer'
$probeDir  = Join-Path $rootDir 'tools\talos-probe'
$mtnDir    = Join-Path $rootDir 'build\eoh_probe\mtn'
$srcJava   = Join-Path $rootDir 'src\main\java\com\EyeOfHarmonyBuffer'
$probesSub = Join-Path $probeDir 'probe'
$shaTool   = [System.Security.Cryptography.SHA256]::Create()
$crlf      = [string]([char]13) + [string]([char]10)

function Get-FileHashHex {
  param([string]$FilePath)
  return [BitConverter]::ToString($shaTool.ComputeHash([IO.File]::ReadAllBytes($FilePath))).Replace('-','')
}
function Get-TextHashHex {
  param([string]$Text)
  return [BitConverter]::ToString($shaTool.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text))).Replace('-','')
}

# ---------- D-CLASSES ----------
$fieldHits = Get-ChildItem -LiteralPath $srcJava -Recurse -File -Filter *.java |
             Select-String -Pattern 'public\s+static\s+boolean\s+\w+\s*='
$allClasses = $fieldHits | ForEach-Object {
  'com.EyeOfHarmonyBuffer.' + ($_.Path.Replace(($srcJava + '\'), '') -replace '\.java$','' -replace '\\','.')
} | Sort-Object -Unique
$keepClasses = @($allClasses | Where-Object { $_ -match '\.(sim|space\.talos)\.' })
$dropClasses = @($allClasses | Where-Object { $_ -notmatch '\.(sim|space\.talos)\.' })
$classListPath = Join-Path $mtnDir 'cfg_classes.txt'
$classHeader = @(
  '# AUTO-GENERATED by fingerprint_config.ps1 -- DO NOT EDIT BY HAND',
  '# source: grep "public static boolean" in src/main/java/com/EyeOfHarmonyBuffer',
  '# kept: sim.** and space.talos.** (production-path statics; the ones P900 can reflect)'
)
Set-Content -LiteralPath $classListPath -Value ($classHeader + $keepClasses) -Encoding ASCII

# ---------- D-SWITCHES ----------
$dumpPath  = Join-Path $mtnDir 'cfg_dump.txt'
$errPath   = Join-Path $mtnDir 'cfg_dump_err.txt'
# P900 must be present in the SHARED out\ tree. It can vanish if another build ran
# `rmdir out` in between, so: try once, and if the dump has no CFG_COUNT, BUILD AND RETRY.
# (Measured 2026-09-19: a stale-tree check alone produced ClassNotFoundException ->
#  SWITCHCOUNT=0 and WORLD=UNKNOWN, i.e. a provenance system reporting 'unknown' for
#  everything. Fail loud, retry once, and never silently emit an empty switch vector.)
function Invoke-P900Dump {
  if (Test-Path -LiteralPath $dumpPath) { Remove-Item -LiteralPath $dumpPath -Force }
  # WORKING DIRECTORY MUST BE THE STAGING DIR, not tools/talos-probe: run_one_probe.bat
  # runs `java -cp out ...`, and `out` lives under build/eoh_probe/mtn. rerun_acceptance.ps1
  # passes -WorkingDirectory $mtn for exactly this reason. Measured 2026-09-19: using the
  # probe dir here yields ClassNotFoundException probe.P900 even though the build succeeded.
  Push-Location $mtnDir
  & (Join-Path $probeDir 'run_one_probe.bat') 'P900' $dumpPath $errPath | Out-Null
  Pop-Location
}
Invoke-P900Dump
$dumpRaw = @()
if (Test-Path -LiteralPath $dumpPath) { $dumpRaw = @(Get-Content -LiteralPath $dumpPath) }
if (-not ($dumpRaw | Where-Object { $_ -match '^CFG_COUNT=' })) {
  if ($NoRebuild) {
    Write-Output 'FATAL_P900_NO_DUMP_NO_REBUILD'
    Get-Content -LiteralPath $errPath -ErrorAction SilentlyContinue | Select-Object -First 4 | ForEach-Object { Write-Output ('  ERR ' + $_) }
    exit 5
  }
  Write-Output 'NOTE_P900_MISSING_OR_STALE_REBUILDING'
  Push-Location $probeDir
  & cmd /c 'runprobe4.bat P900 --build-only' | Out-Null
  Pop-Location
  Invoke-P900Dump
  $dumpRaw = @()
  if (Test-Path -LiteralPath $dumpPath) { $dumpRaw = @(Get-Content -LiteralPath $dumpPath) }
}
$dumpLines = @($dumpRaw | Where-Object { $_ -match '^CFG_' } | Sort-Object)
if (-not ($dumpRaw | Where-Object { $_ -match '^CFG_COUNT=' })) {
  Write-Output 'FATAL_P900_NO_DUMP'
  Get-Content -LiteralPath $errPath -ErrorAction SilentlyContinue | Select-Object -First 4 | ForEach-Object { Write-Output ('  ERR ' + $_) }
  exit 5
}
$switchBlock = ($dumpLines -join '|')
# SWITCHCOUNT MUST COUNT SWITCHES, NOT HOUSEKEEPING. Measured 2026-09-19: the earlier
# pattern '^CFG_[A-Za-z]' also matched CFG_BEGIN / CFG_END / CFG_COUNT= / CFG_CLASSES= /
# CFG_LOAD_FAIL= (and CFG_ERROR= / CFG_HINT= when P900 fails), so the reported number
# was 67 while P900's own CFG_COUNT= said 62 -- the headline 'how many switches are in
# the measurement identity' figure was itself off by five housekeeping lines.
# The aggregate below ($switchBlock) is UNCHANGED, so CFGFP is byte-identical across
# this fix (verified by re-running the collector and comparing CFGFP).
$switchMeta  = @('CFG_BEGIN','CFG_END','CFG_COUNT=','CFG_CLASSES=','CFG_LOAD_FAIL=','CFG_CLASS_LOAD_FAIL=','CFG_ERROR=','CFG_HINT=')
$switchCount = 0
foreach ($swLine in $dumpLines) {
  $isMeta = $false
  foreach ($swTag in $switchMeta) { if ($swLine.StartsWith($swTag)) { $isMeta = $true } }
  if (-not $isMeta) { $switchCount = $switchCount + 1 }
}
$swWarn = ''
$cfgCountLine = $dumpRaw | Where-Object { $_ -match '^CFG_COUNT=' } | Select-Object -First 1
if ($cfgCountLine) {
  $cfgCountVal = [int](($cfgCountLine -split '=')[1])
  if ($cfgCountVal -ne $switchCount) { $swWarn = 'WARN_SWITCHCOUNT_VS_P900 counted=' + $switchCount + ' p900=' + $cfgCountVal }
}

# ---------- WORLD label: MEASURED, never inferred from env ----------
# SECTION 567: the switch PlateField.TALOS_TERRAIN was deleted with the legacy terrain; the
# world identity bit is now PlateField.WORLD_IS_TALOS (a provenance constant, not a knob).
$worldLine = $dumpLines | Where-Object { $_ -match 'PlateField\.WORLD_IS_TALOS=' } | Select-Object -First 1
$worldLabel = 'UNKNOWN'
if ($worldLine) {
  if ($worldLine -match '=true')  { $worldLabel = 'TALOS' }
  if ($worldLine -match '=false') { $worldLabel = 'LEGACY' }
}

# ---------- D-PROBES ----------
$probeFiles = @(Get-ChildItem -LiteralPath $probesSub -File -Filter *.java | Sort-Object Name)
$probeBuilder = New-Object System.Text.StringBuilder
foreach ($pf in $probeFiles) {
  [void]$probeBuilder.Append((Get-FileHashHex $pf.FullName).Substring(0,16) + '  ' + $pf.Name + $crlf)
}
foreach ($rf in @('runp.bat','runprobe4.bat','run_one_probe.bat','rerun_acceptance.ps1')) {
  $rp = Join-Path $probeDir $rf
  if (Test-Path -LiteralPath $rp) { [void]$probeBuilder.Append((Get-FileHashHex $rp).Substring(0,16) + '  ' + $rf + $crlf) }
}
$probeFp = (Get-TextHashHex $probeBuilder.ToString()).Substring(0,32)

# ---------- D-ENV ----------
$envParts = @()
# SECTION 567: EOH_TALOS_TERRAIN was dropped from the whitelist together with the switch it
# fed; leaving it in would keep hashing a variable that can no longer change anything.
foreach ($ev in @('EOH_PROBE_JOBS')) {
  $val = [System.Environment]::GetEnvironmentVariable($ev,'Process')
  if ($null -eq $val) { $envParts += ($ev + '=<unset>') } else { $envParts += ($ev + '=' + $val) }
}
$envBlock = ($envParts -join '|')

# ---------- D-SEED (PROXY) ----------
$bareSeed = 0
foreach ($pf in $probeFiles) {
  $bareSeed += ([regex]::Matches([IO.File]::ReadAllText($pf.FullName), '1022228679L')).Count
}

# ---------- D-CONFIG ----------
$forgeCfg  = Join-Path $rootDir 'run\config\TalosConfig.cfg'
$forgePart = 'ABSENT'
if (Test-Path -LiteralPath $forgeCfg) { $forgePart = (Get-FileHashHex $forgeCfg).Substring(0,32) }

# ---------- SRC fingerprint (existing recipe, read-only) ----------
$srcFpPath = Join-Path $mtnDir 'SOURCE_FINGERPRINT.txt'
$srcFp = 'MISSING'
if (Test-Path -LiteralPath $srcFpPath) {
  $srcLine = Get-Content -LiteralPath $srcFpPath -TotalCount 1
  $srcFp = ($srcLine -split '=')[1].Trim().Split(' ')[0]
}

# ---------- aggregate ----------
$aggText = @(
  'SRC='    + $srcFp,
  'PROBES=' + $probeFp,
  'SWITCH=' + (Get-TextHashHex $switchBlock),
  'ENV='    + (Get-TextHashHex $envBlock),
  'CONFIG=' + $forgePart
) -join $crlf
$cfgFp = (Get-TextHashHex $aggText).Substring(0,32)

$head = @(
  'CFGFP='       + $cfgFp,
  'SRCFP='       + $srcFp,
  'PROBEFP='     + $probeFp,
  'WORLD='       + $worldLabel,
  'SWITCHCOUNT=' + $switchCount,
  'SEEDBARE='    + $bareSeed,
  'FORGECFG='    + $forgePart,
  'ENVBLOCK='    + $envBlock,
  'GENERATED='   + (Get-Date -Format s)
)
[IO.File]::WriteAllText((Join-Path $mtnDir 'CFG_FINGERPRINT.txt'), (($head + $aggText) -join $crlf) + $crlf, [Text.UTF8Encoding]::new($false))

$head | ForEach-Object { Write-Output $_ }
Write-Output ('EXCLUDED_CLASSES=' + $dropClasses.Count)
if ($swWarn -ne '')             { Write-Output $swWarn }
if ($bareSeed -gt 0)            { Write-Output 'WARN_SEED_BARE_LITERALS_PRESENT' }
if ($worldLabel -eq 'UNKNOWN')  { Write-Output 'WARN_WORLD_UNKNOWN' }
if ($switchCount -lt 40)        { Write-Output 'WARN_SWITCH_COUNT_LOW' }
